spring:
  application:
    name: security-server
  web:
    resources:
      static-locations: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.wzdsl.com:13316/xmd_security?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: 6DYPN426Hx@*iL
  main:
    allow-bean-definition-overriding: true

#自定义配置
com:
  xmd:
    web:
      #
      ignoring:
        # swagger
        - /swagger-ui.html
        - /swagger-ui/*
        - /swagger-resources/**
        - /v2/api-docs
        - /v3/api-docs
        - /webjars/**
#   #jwt认证信息
    jwt:
      login-url: /login
      jwt-expiration: 28800
      white-list:
        - /index.html
        - /binding.html
        - /qqLogin/**
        # swagger
        - /v3/api-docs/**
        - /doc.html
        # 端点请求
        - /monitor/**
#    #社交登陆配置
    social:
      qq:
        app-id: 100550231
        appSecret: 69b6ab57b22f3c2fe6a6149274e3295e
        provider-id: callback.do
      github:
        app-id: Iv1.9a1d0cbafea21da5
        secret: ce2ff0d7357e60cb05f4479b2591ba96b36bf038
        provider-id: github
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
        provider-id: weixin
#      filter-processes-url: /social
      filter-processes-url: /qqLogin
      redirect-uri: 'http://www.pinzhi365.com/qqLogin'

springdoc:
  swagger-ui:
    # 禁止默认路径
    disable-swagger-default-url: true

server:
  port: 9999
#  port: 80
  servlet:
    context-path: /api


# 端点服务（actuator）
management:
  endpoints:
    web:
      exposure:
        # 指定开发端点
        include: info,health,threaddump,metrics,prometheus
      # 修改默认请求路径
      base-path: /monitor
      # 排除 shutdown
      exclude: shutdown
  endpoint:
    health:
      # 在health地址下面，显示db、redis、rabbit连接情况等
      show-details: always


