

spring:
  web:
    resources:
      static-locations: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.71.136.187:13316/security?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: lx63024477
  main:
    allow-bean-definition-overriding: true


com:
  xmd:
#   #jwt认证信息
    jwt:
      login-url: /login
      jwt-expiration: 28800
      white-list:
        - /index.html
        - /binding.html
        - /qqLogin/**
#    #社交登陆配置
    social:
      qq:
        app-id: 100550231
        appSecret: 69b6ab57b22f3c2fe6a6149274e3295e
        provider-id: callback.do
      github:
        app-id: Iv1.9a1d0cbafea21da5
        secret: ce2ff0d7357e60cb05f4479b2591ba96b36bf038
        provider-id: github
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
        provider-id: weixin
#      filter-processes-url: /social
      filter-processes-url: /qqLogin
      redirect-uri: 'http://www.pinzhi365.com/qqLogin'


server:
  port: 9999
#  port: 80
#  servlet:
#    context-path: /api/co/